### ISSUE TITLE
Ubuntu22.04 repo is missing InRelease file and thus not working.

### ISSUE THREAD

**Issue by PorkCharsui79** [NVIDIA/nvidia-container-toolkit#96] opened 2023-08-14 12:37 UTC
https://nvidia.github.io/libnvidia-container/stable/ubuntu22.04/amd64/InRelease
Repo is missing InRelease file and thus not working. Please fix ASAP.

**Comment by elezar** [comment] 2023-08-14 12:57
This is a duplicate of #89

**Comment by PorkCharsui79** [comment] 2023-08-14 13:05
https://wiki.debian.org/DebianRepository
Please read that and set up a repository the way it's supposed to be!

**Comment by PorkCharsui79** [comment] 2023-08-14 13:06
these nvidia repositories have been a pain in the @$$ since they've existed. Please conform to Debian standards to make everyones life better.

**Comment by PorkCharsui79** [comment] 2023-08-14 13:16
Very logical! Who wouldn't think of using ubuntu18.04 on their Debian11 machine.

**Comment by elezar** [comment] 2023-08-14 13:26
@PorkCharsui79 I referred you to that issue since you mention Ubuntu 22.04 in your issue description.

Note that the instructions for downloading the repo `.list` files (that include `${distribution}`) should still be valid. If you have specific steps that are not working as expected, please call these out so that we can provide further assistence.

**Comment by PorkCharsui79** [comment] 2023-08-14 13:27
Please learn to set up a repository the proper way.

**Comment by elezar** [comment] 2023-08-14 13:32
> Please learn to set up a repository the proper way.

If you have a constructive suggestion for how to migrate the existing repository structure to a new compliatn one while mantaining compatibility for the majority of users, feel free to create an issue outlining the steps and propose PRs to contribute.

**Comment by PorkCharsui79** [comment] 2023-08-14 13:36
you cannot just decide you don't want to duplicate your repo's anymore and remove the ones you have. People are using those and by removing them you're breaking they systems. I've configured your repo's on 100's of machines for our users... apt broke on all those systems, because you removed a repo without warning (or common sense).

Debian has very thoroughly thought out how to setup a repository, use their documentation for detailed instructions on how to set up and/or migrate your current repo's:
https://wiki.debian.org/DebianRepository

**Comment by PorkCharsui79** [comment] 2023-08-14 13:44
And when will you change the repository name again, so I can already prepare for the next time apt breaks?

**Closed** 2023-08-14 14:00 UTC
