### ISSUE TITLE
Mount Vulkan icd.d JSON file into the container

### ISSUE THREAD

**Issue by bmerry** [NVIDIA/nvidia-container-toolkit#16] opened 2022-02-26 15:27 UTC
The Vulkan loader uses JSON files to locate vendor implementations. For example, on my host, /usr/share/vulkan/icd.d/nvidia_icd.json contains
```
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.194"
    }
}
```
Crucially, the file needs to contain the Vulkan API version that's implemented by libGLX_nvidia.so.0, and that is mounted from the host and hence can't be baked into the container (https://gitlab.com/nvidia/container-images/vulkan does anyway, but presumably it will be the wrong version unless you happen to have a specific driver version). It would be preferable if nvidia-container-toolkit could automatically mount the file from the host.

There is a similar issue for /usr/share/glvnd/egl_vendor.d/10_nvidia.json, but that doesn't bake in an API version so it can be stored inside the container - provided NVIDIA never change the name of the library. Since the library it points at is mounted from the host, it still seems logical to have that JSON file mounted from the host to match.

**Comment by elezar** [comment] 2022-10-24 11:43
Hi @bmerry we are working at improving this in the next release of the NVIDIA Container Toolkit. The next version of the NVIDIA Container Toolkit (`v1.12.0-rc.1`) that is available from our experimental repositories includes initial support for injecting the loaders using the NVIDIA Contianer Runtime.

Would you be willing to test this. Note that the automatic injection of Rendering devices (`/dev/dri/card*` and `/dev/dri/renderD*`) is still being worked on.

**Comment by bmerry** [comment] 2022-10-24 12:19
Thanks @elezar. I'll try to find time to test it in the next week or so. I should mention that my use case makes very minimal use of Vulkan and doesn't really depend on newer features, so it might not be the most thorough test.

**Comment by bmerry** [comment] 2022-10-25 06:47
@elezar I've given that release candidate a test and it seems to work as expected - I removed the steps from my Dockerfile that prepared these JSON files, and was still able to run some Vulkan code. I'm only using Vulkan for compute, not rendering, so didn't need `/dev/dri*`. Thanks!

**Comment by elezar** [comment] 2022-10-25 09:29
Great to hear! For reference the work to include the devices is in progress [here](https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/merge_requests/219).

I will update this issue once the final 1.12.0 release is out.

**Comment by rp42** [comment] 2022-10-25 11:28
Great news. I've not managed to get it to work for me yet though. I have installed version 1.12.0~rc.1-1 on Ubuntu 20. If I remove my hardcoded nvidia_icd.json from my container, then vulkaninfo fails. I don't see any  likely looking files mounted into the container:
`$ docker run --gpus all -it --rm nvidia/cudagl:11.4.2-runtime-ubuntu20.04 find / -iname '*nvidia*.json*'
/usr/share/glvnd/egl_vendor.d/10_nvidia.json`
Is there something else I need to do? Thanks!

**Comment by elezar** [comment] 2022-10-25 12:05
@rp42 please ensure that the NVIDIA Container Runtime is configured as a docker runtime and that this is selected. This new functionality requires that the runtime be used, and does not support the injection of the NVIDIA Container Runtime hook via the `--gpus` flag.

Assuming that your `/etc/docker/daemon.json` looks as follows:
```json
{
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    }
}
```
(and you have restarted the docker daemon), you should be able to run:
```
docker run --runtime=nvidia --gpus all -it --rm nvidia/cudagl:11.4.2-runtime-ubuntu20.04 find / -iname '*nvidia*.json*'
```
Also note that this behaviour is only triggered if the `NVIDIA_DRIVER_CAPABILITIES` environment variable include `graphics` or `display` (or `all`), so if the above command does not work you could try adding `-e NVIDIA_DRIVER_CAPABILITIES=all` to the command above.

**Comment by rp42** [comment] 2022-10-25 12:35
Thanks. The `--runtime=nvidia` is what I was missing. With that option, our Vulkan rendering app works without including the JSON ICD in the Docker image.

**Comment by dualvtable** [comment] 2022-10-25 19:20
And could you also comment on whether you used the Vulkan image ( based off the code in https://gitlab.com/nvidia/container-images/vulkan ) for your testing? FWIW, the repo was updated to not bake in any JSONs.

**Comment by bmerry** [comment] 2022-10-25 19:33
> And could you also comment on whether you used the Vulkan image ( based off the code in https://gitlab.com/nvidia/container-images/vulkan ) for your testing? FWIW, the repo was updated to not bake in any JSONs.

I was using an image based on `nvidia/cuda:11.4.1-devel-ubuntu20.04`, with `graphics` added to `NVIDIA_DRIVER_CAPABILITIES`.

**Comment by dualvtable** [comment] 2022-10-25 19:44
Thanks for the update - I was trying to determine if the Vulkan code we built was of any value or not. Do you expect to use the Vulkan as a base image going forward?

**Comment by bmerry** [comment] 2022-10-25 20:01
> Do you expect to use the Vulkan as a base image going forward?

Probably not, just because we have something that works and don't want to fix what isn't broken. It also looks like the Vulkan image is based off the base CUDA image rather than the devel image that we currently use.

**Comment by maxpain** [comment] 2022-12-19 15:18
Any workaround for v1.11.0 users?

**Comment by elezar** [comment] 2023-02-06 10:59
We have released `v1.12.0` which includes the injection of Vulkan ICD files and can be run using the instructions from https://github.com/NVIDIA/nvidia-container-toolkit/issues/16#issuecomment-1290439475.

@bmerry  I am closing this issue, but please reopen it if there are still problems.

@maxpain for `v1.11.0` users the files would have to be manually injected from the host.

**Closed by elezar** 2023-02-06 10:59 UTC

**Comment by maxpain** [comment] 2023-07-08 14:35
@elezar I upgraded to `v1.12.1` and trying to run `vulkaninfo --summary`, but getting these errors:
```
root@csgo-0:/lib/x86_64-linux-gnu# vulkaninfo --summary
ERROR: [Loader Message] Code 0 : libXext.so.6: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON libGLX_nvidia.so.0. Ignoring this JSON
ERROR: [Loader Message] Code 0 : libXext.so.6: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON libGLX_nvidia.so.0. Ignoring this JSON
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
```

Does `nvidia-container-runtime` mount `libGLX_nvidia.so.0` from the host to the container?

**Comment by elezar** [comment] 2023-07-10 09:28
> @elezar I upgraded to `v1.12.1` and trying to run `vulkaninfo --summary`, but getting these errors:
> 
> ```
> root@csgo-0:/lib/x86_64-linux-gnu# vulkaninfo --summary
> ERROR: [Loader Message] Code 0 : libXext.so.6: cannot open shared object file: No such file or directory
> ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON libGLX_nvidia.so.0. Ignoring this JSON
> ERROR: [Loader Message] Code 0 : libXext.so.6: cannot open shared object file: No such file or directory
> ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON libGLX_nvidia.so.0. Ignoring this JSON
> error: XDG_RUNTIME_DIR is invalid or not set in the environment.
> ```
> 
> This file is present in `/usr/lib/x86_64-linux-gnu`, but `vulkaninfo` doesn't use it.
> 
> ```
> root@csgo-0:/usr/lib/x86_64-linux-gnu# ls | grep libGLX
> libGLX_indirect.so.0
> libGLX_nvidia.so.0
> libGLX_nvidia.so.535.54.03
> ```
> 
> UPD: I've installed `libxext6` and now It's working!

Glad you go it working. Do you mean that you installed `libext6` in the container?

**Comment by maxpain** [comment] 2023-07-10 09:35
@elezar Yes.

**Comment by qhaas** [comment] 2024-08-31 20:50
Had some trouble with the ICDs when running headless (i.e. command-line only) with Ubuntu 22.04 containers.

Host:
```
$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.4 (Plow)

$ nvidia-smi -L
GPU 0: NVIDIA GeForce GTX 1650 with Max-Q Design (UUID: GPU-93004254-1053-96c5-3486-8e39ffb59c8f)

$ vulkaninfo --summary | grep 'NVIDIA GeForce'
 deviceName         = NVIDIA GeForce GTX 1650 with Max-Q Design

$ cat /etc/docker/daemon.json 
{
    "data-root": "/home/docker",
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "nvidia-container-runtime"
        }
    }
}

$ nvidia-container-toolkit --version
NVIDIA Container Runtime Hook version 1.16.1

$ docker version
...
Engine:
  Version:          25.0.0
...
containerd:
  Version:          1.6.27
...
runc:
  Version:          1.1.11
...
docker-init:
  Version:          0.19.0
```

Based on the example above, we see the expected ICDs are present:
```
$ docker run -e NVIDIA_DRIVER_CAPABILITIES=all --runtime=nvidia --gpus all -it --rm ubuntu:22.04 find / -iname '*nvidia*.json*'
/usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json
/usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json
/usr/share/glvnd/egl_vendor.d/10_nvidia.json
```

But, vulkan doesn't seem to load them correctly(?), we modify the image to get the appropriate packages `vulkan-tools mesa-utils` (which includes `libxext6` noted above):
```
$ cat Dockerfile
FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y vulkan-tools mesa-utils && apt-get clean
$ docker build -t test:vulkan .
...
$ docker run -e NVIDIA_DRIVER_CAPABILITIES=all --runtime=nvidia --gpus all -it --rm --name vulkan test:vulkan
# nvidia-smi -L
GPU 0: NVIDIA GeForce GTX 1650 with Max-Q Design (UUID: GPU-93004254-1053-96c5-3486-8e39ffb59c8f)
...
# vulkaninfo --summary | grep 'NVIDIA GeForce'
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 4.  Skipping ICD.
'DISPLAY' environment variable not set... skipping surface info
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
```

I'm running headless (i.e. command-line only), so wayland / X shouldn't matter, only EGL(?).  Regardless, copying `/usr/share/vulkan/icd.d/nvidia_icd.x86_64.json` from the host (or rather, the cuda EL9 repo's `nvidia-driver-libs` package) into the container allows the vulkan compatible gpu to be detected by `vulkaninfo`.  On the host:
```
$ cat /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.242"
    }
}

$ docker cp /usr/share/vulkan/icd.d/nvidia_icd.x86_64.json vulkan:/usr/share/vulkan/icd.d/
...
```
Back to the container:
```
# vulkaninfo --summary | grep 'NVIDIA GeForce'
WARNING: [Loader Message] Code 0 : terminator_CreateInstance: Failed to CreateInstance in ICD 4.  Skipping ICD.
'DISPLAY' environment variable not set... skipping surface info
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
error: XDG_RUNTIME_DIR not set in the environment.
	deviceName         = NVIDIA GeForce GTX 1650 with Max-Q Design
```

**Comment by samohovets** [comment] 2024-11-12 18:56
The issue is still relevant for platforms like [Fly.io](https://fly.io/gpu) or [Google Cloud Run](https://cloud.google.com/run/docs/configuring/services/gpu).

I have no idea how they run their containers, but here's a workaround to make Vulkan recognize NVIDIA GPUs:

1. Run `nvidia-smi` to check the driver version that is currently mounted into the container
2. Go to the NVIDIA website and get the download link to the exact driver that `nvidia-smi` shows
3. Install it manually in your Dockerfile, example:

```Dockerfile
RUN wget https://us.download.nvidia.com/tesla/535.216.01/NVIDIA-Linux-x86_64-535.216.01.run
RUN chmod +x NVIDIA-Linux-x86_64-535.216.01.run
RUN ./NVIDIA-Linux-x86_64-535.216.01.run --silent --no-kernel-module
RUN rm NVIDIA-Linux-x86_64-535.216.01.run
```
This will install the required libs and set configs for Vulcan, e.g it will create the right `/etc/vulkan/icd.d/nvidia_icd.json` since it's not mounted by default. 

After this, you should be able to see your GPU in `vulkaninfo --summary`.
