### ISSUE TITLE
Ubuntu 22.04 release file missing?

### ISSUE THREAD

**Issue by battlesnake** [NVIDIA/nvidia-container-toolkit#91] opened 2023-08-10 13:02 UTC
`apt update` failed:
```
E: The repository 'https://nvidia.github.io/libnvidia-container/stable/ubuntu22.04/amd64  Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

https://nvidia.github.io/libnvidia-container/stable/ubuntu22.04/amd64 now shows:
```
# Unsupported distribution!
# Check https://nvidia.github.io/libnvidia-container
```

But on the ["official documentation" page](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) linked from [the page in that response](https://nvidia.github.io/libnvidia-container), Ubuntu 22.04 amd64 is shown as supported, with note:

```
(%) Ubuntu 20.04 and Ubuntu 22.04 packages are symlinked (redirected) to ubuntu18.04
```

**Comment by elezar** [comment] 2023-08-10 13:09
This is a duplicate of https://github.com/NVIDIA/nvidia-container-toolkit/issues/89.

Please see the instructions there.

Note that the official instructions refer to downloading the repository list for the supported platforms which in the `ubuntu22.04` case will reference the (still valid) `ubuntu18.04` repositories.

**Closed** 2023-08-10 14:16 UTC
